export const ICON_LABELS = {
  Logo: "Логотип",
  TickRight: "Галочка вправо",
  Notification: "Уведомление",
  Search: "Поиск",
  ArrowTop: "Стрелка вверх",
  Home: "Дом",
  RedDot: "Красная точка",
  Location: "Локация",
  Eye: "Глаз",
  Pen: "Ручка",
  Projects: "Проекты",
  Folder: "Папка",
  Chat: "Чат",
  Calendar: "Календарь",
  Graph: "График",
  Bag: "Сумка",
  Users: "Пользователи",
  Materials: "Материалы",
  Settings: "Настройки",
  Moon: "Луна",
  Sun: "Солнце",
  GreenDot: "Синяя точка",
  TickLeft: "Галочка влево",
  TickTop: "Галочка вверх",
  TickBottom: "Галочка вниз",
  Diagram: "Диаграмма",
  Share: "Отправить",
  LogoText: "Лого текст",
  MadeByTools: "Сделано Tools",
  Email: "Емаил",
  Password: "Пароль",
  Control: "Контроль",
  CheckMark: "Чекмарк",
  EyeClosed: "Глаз закртый",
  Verified: "Верифицирован",
  Close: "Закрыть",
  File: "Файл",
  Delete: "Удалить",
  Edit: "Редактировать",
  Dots: "Точки",
  Export: "Экспорт",
  Click: "Клик",
  Podryad: "Подряд",
  Inspection: "Инспекция",
  Plus: "Плюс",
  Map: "Карта",
  LocationAdd: "Добавить локацию",
  Download: "Скачать",
  Phone: "Телефон",
} as const;

export type IconName = keyof typeof ICON_LABELS;
