services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: construct_frontend_dev_image:latest
    container_name: construct_frontend_dev
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
